### ISSUE TITLE
Categories and taxonomies support?

### ISSUE THREAD

**Issue by vol4ikman** [ArtifexTech/life-jacket#1]

**Comment by nickgagne** [comment]
Could you provide an example of how this would be incorporated into the Life Jacket framework?

**Comment by vol4ikman** [comment]
I need a posts catalog by categories

**Comment by mitchartifextech** [comment]
Currently, Lifejacket doesn't support Taxonomies. However, it could be a feature in the future. We are really just starting with the most basic version of it at this point, but we promise to improve it over time. 

LJ wasn't really intended to be a full robust CMS either, so you might want to use Wordpress or something that is more of a CMS. LJ is more of a static website generator than it is CMS, similar to Jekyll in that regard.
